"$schema" = "./node_modules/wrangler/config-schema.json"

main = ".open-next/worker.js"
name = "eguchi-pitch-training"
compatibility_date = "2026-06-10"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "pitch-patch.bradstalcup.com", custom_domain = true },
]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"


[[hyperdrive]]
binding = "HYPERDRIVE"
id = "72b4657596e84b7eadf9eb6615d047dd"
