import type { ChordDefinition } from "./types";

export const DEFAULT_CHORD_DEFINITIONS = [
  {
    id: "white-red-ceg",
    slug: "white-red-ceg",
    name: "Red chord",
    rootNote: "C",
    quality: "major",
    inversion: 0,
    midiNotes: [60, 64, 67],
    displayNotes: ["C", "E", "G"],
    sortOrder: 1,
    isDefault: true,
  },
  {
    id: "white-yellow-cfa",
    slug: "white-yellow-cfa",
    name: "Yellow chord",
    rootNote: "F",
    quality: "major",
    inversion: 1,
    midiNotes: [60, 65, 69],
    displayNotes: ["C", "F", "A"],
    sortOrder: 2,
    isDefault: true,
  },
  {
    id: "white-blue-bdg",
    slug: "white-blue-bdg",
    name: "Blue chord",
    rootNote: "G",
    quality: "major",
    inversion: 1,
    midiNotes: [59, 62, 67],
    displayNotes: ["B", "D", "G"],
    sortOrder: 3,
    isDefault: true,
  },
  {
    id: "white-black-acf",
    slug: "white-black-acf",
    name: "Black chord",
    rootNote: "F",
    quality: "major",
    inversion: 2,
    midiNotes: [57, 60, 65],
    displayNotes: ["A", "C", "F"],
    sortOrder: 4,
    isDefault: true,
  },
  {
    id: "white-green-dgb",
    slug: "white-green-dgb",
    name: "Green chord",
    rootNote: "G",
    quality: "major",
    inversion: 2,
    midiNotes: [62, 67, 71],
    displayNotes: ["D", "G", "B"],
    sortOrder: 5,
    isDefault: true,
  },
  {
    id: "white-orange-egc",
    slug: "white-orange-egc",
    name: "Orange chord",
    rootNote: "C",
    quality: "major",
    inversion: 1,
    midiNotes: [64, 67, 72],
    displayNotes: ["E", "G", "C"],
    sortOrder: 6,
    isDefault: true,
  },
  {
    id: "white-purple-fac",
    slug: "white-purple-fac",
    name: "Purple chord",
    rootNote: "F",
    quality: "major",
    inversion: 0,
    midiNotes: [65, 69, 72],
    displayNotes: ["F", "A", "C"],
    sortOrder: 7,
    isDefault: true,
  },
  {
    id: "white-pink-gbd",
    slug: "white-pink-gbd",
    name: "Pink chord",
    rootNote: "G",
    quality: "major",
    inversion: 0,
    midiNotes: [67, 71, 74],
    displayNotes: ["G", "B", "D"],
    sortOrder: 8,
    isDefault: true,
  },
  {
    id: "white-brown-gce",
    slug: "white-brown-gce",
    name: "Brown chord",
    rootNote: "C",
    quality: "major",
    inversion: 2,
    midiNotes: [67, 72, 76],
    displayNotes: ["G", "C", "E"],
    sortOrder: 9,
    isDefault: true,
  },
  {
    id: "black-csharp-major",
    slug: "black-csharp-major",
    name: "C sharp chord",
    rootNote: "C#",
    quality: "major",
    inversion: 0,
    midiNotes: [61, 65, 68],
    displayNotes: ["C#", "F", "G#"],
    sortOrder: 10,
    isDefault: true,
  },
  {
    id: "black-dsharp-major",
    slug: "black-dsharp-major",
    name: "D sharp chord",
    rootNote: "D#",
    quality: "major",
    inversion: 0,
    midiNotes: [63, 67, 70],
    displayNotes: ["D#", "G", "A#"],
    sortOrder: 11,
    isDefault: true,
  },
  {
    id: "black-fsharp-major",
    slug: "black-fsharp-major",
    name: "F sharp chord",
    rootNote: "F#",
    quality: "major",
    inversion: 0,
    midiNotes: [66, 70, 73],
    displayNotes: ["F#", "A#", "C#"],
    sortOrder: 12,
    isDefault: true,
  },
  {
    id: "black-gsharp-major",
    slug: "black-gsharp-major",
    name: "G sharp chord",
    rootNote: "G#",
    quality: "major",
    inversion: 0,
    midiNotes: [68, 72, 75],
    displayNotes: ["G#", "C", "D#"],
    sortOrder: 13,
    isDefault: true,
  },
  {
    id: "black-asharp-major",
    slug: "black-asharp-major",
    name: "A sharp chord",
    rootNote: "A#",
    quality: "major",
    inversion: 0,
    midiNotes: [70, 74, 77],
    displayNotes: ["A#", "D", "F"],
    sortOrder: 14,
    isDefault: true,
  },
] as const satisfies readonly ChordDefinition[];

export type DefaultChordSlug = (typeof DEFAULT_CHORD_DEFINITIONS)[number]["slug"];

export function getDefaultChordDefinition(slug: string): ChordDefinition | undefined {
  return DEFAULT_CHORD_DEFINITIONS.find((chord) => chord.slug === slug);
}
